# Generated by Django 5.0 on 2023-12-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_pic',
            field=models.FileField(default='sad.jpg', upload_to='buyer_pics'),
        ),
    ]
